server:
  port: 8088
spring:
  application:
    name: Pago

  datasource:
    url: jdbc:mysql://localhost:3307/pago
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

