spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/auth?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  cloud:
    gateway:
      mvc:
        routes:
          - id: monopatin
            uri: http://localhost:8083
            predicates:
              - Path=/monopatines/**
          - id: mapa
            uri: http://localhost:8087
            predicates:
              - Path=/mapa/**
          - id: mantenimiento
            uri: http://localhost:8082
            predicates:
              - Path=/mantenimiento/**
          - id: pago
            uri: http://localhost:8088
            predicates:
              - Path=/pago/**
          - id: parada
            uri: http://localhost:8085
            predicates:
              - Path=/parada/**
          - id: reporte
            uri: http://localhost:8086
            predicates:
              - Path=/reporte/**
          - id: usuario
            uri: http://localhost:8081/usuarios
            predicates:
              - Path=/usuarios/**
          - id: viaje
            uri: http://localhost:8084
            predicates:
              - Path=/viaje/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
