server:
  port: 8084
spring:
  application:
    name: Viaje

  datasource:
    url: jdbc:mysql://localhost:3306/viaje
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

