server:
  port: 8081
spring:
  application:
    name: Usuario

  datasource:
    url: jdbc:mysql://localhost:3306/usuarios?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true